### ISSUE TITLE
In the main example given: TypeError: type object argument after ** must be a mapping, not str

### ISSUE THREAD

**Issue by neatville** [PapyrusThePlant/strawpoll.py#6]
```
<ipython-input-8-84b98d8870fc> in main()
     35 
     36     # Submitting it on strawpoll
---> 37     p2 = await api.submit_poll(p2)
     38     print(p2.id)                # 10921552
     39     print(p2.url)               # http://www.strawpoll.me/10921552

~/path/to/env/lib/python3.6/site-packages/strawpoll/http.py in request_async(self, method, url, **kwargs)
     65                 raise HTTPException(resp, rdata)
     66             elif cls is not None:
---> 67                 return cls(**rdata)
     68             else:
     69                 return rdata

TypeError: type object argument after ** must be a mapping, not str
```
Python 3.6 here. I'm not sure what needs to be different.

**Comment by jwshields** [comment]
What is the `p2` in line 37? How did you create that object? 

Here's a snippet from my code which works.
`arglist` is a list
`title` is a string

```
        spoll_api = strawpoll.API()
        topoll = strawpoll.Poll(title, arglist, multi=False)
        return_poll = await spoll_api.submit_poll(poll=topoll)
        print(return_poll.url)
```

**Comment by neatville** [comment]
I copied and pasted the example given here into iPython, not modifying it in any way: https://github.com/PapyrusThePlant/strawpoll.py/blob/master/examples/polls.py  
The full results:

```
10915632
http://www.strawpoll.me/10915632
awesome?
[('fuck yes', 5), ('yes', 0)]
['yes', 'fuck yes']
[0, 5]
5
[('fuck yes', 5)]
('yes', 0)
('fuck yes', 5)
False
normal
False
None

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-4ba28ea0ed72> in <module>()
     39 
     40 
---> 41 asyncio.get_event_loop().run_until_complete(main())

/usr/lib/python3.6/asyncio/base_events.py in run_until_complete(self, future)
    466             raise RuntimeError('Event loop stopped before Future completed.')
    467 
--> 468         return future.result()
    469 
    470     def stop(self):

<ipython-input-2-4ba28ea0ed72> in main()
     34 
     35     # Submitting it on strawpoll
---> 36     p2 = await api.submit_poll(p2)
     37     print(p2.id)                # 10921552
     38     print(p2.url)               # http://www.strawpoll.me/10921552

~/path/to/env/lib/python3.6/site-packages/strawpoll/http.py in request_async(self, method, url, **kwargs)
     65                 raise HTTPException(resp, rdata)
     66             elif cls is not None:
---> 67                 return cls(**rdata)
     68             else:
     69                 return rdata

TypeError: type object argument after ** must be a mapping, not str

```
I'm not sure if the user is expected to change anything, even when running examples. While I am used to Python, I happen to not be used to async functions. I thought I'd point that out since the code here: https://github.com/PapyrusThePlant/strawpoll.py/blob/master/examples/request_policy.py gave me this warning:  
```
/path/to/env/lib/python3.6/site-packages/strawpoll/http.py:45: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  self.session_async.close()
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2c3ed25a58>
Unclosed connector
```
That's part of the output I got back, the rest of it was pretty similar.

**Comment by MJJBennett** [comment]
Hi, the reason you're receiving this error is because Strawpoll has modified their API so that it no longer works with HTTP (only HTTPS). The actual reason for your error is that, instead of receiving the json object that would normally be returned by Strawpoll's API (and can be 'unwrapped' with **), you're actually receiving a large string containing their 404 (or whichever) error page.

You can easily fix this by making the same change as I've made [here](https://github.com/PapyrusThePlant/strawpoll.py/pull/5). Basically, there's one file where you change an `http` to an `https`.

Regarding the aiohttp issues, I haven't been able to fix them yet (no time) but they are unrelated - they have to do with (as far as I can tell) the fact that the library is creating async objects in synchronous methods, but it's not really a problem (you just have to ignore the warnings, until there's something to fix them.)

Hope this helps!

Edit: Do let me know if this doesn't fix your problem, I'm kind of confused that @jwshields was able to run a poll creation without an issue. It shouldn't be possible to do POST requests at this point to Strawpoll's API with HTTP.

**Comment by neatville** [comment]
Thanks to both of you for your responses.   
@MJJBennett, That seems to have helped. Although the actual errors are gone, I still get these warnings: 

```
/path/to/env/lib/python3.6/site-packages/strawpoll/http.py:45: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  self.session_async.close()
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f088e649ef0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f088e5107f0>, 14719.347237668)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f088dc754e0>
```
Tested on the same example code that's shown on here. But again, I'm someone who is inexperienced with coroutines.

**Comment by MJJBennett** [comment]
@neatville You might not have seen my edit, but that is unrelated. As I said in the edit:

>Regarding the aiohttp issues, I haven't been able to fix them yet (no time) but they are unrelated - they have to do with (as far as I can tell) the fact that the library is creating async objects in synchronous methods, but it's not really a problem (you just have to ignore the warnings, until there's something to fix them.)

In a really simple way (at least, what I think it's doing): Basically, it's creating (and, later, stopping) an 'async' object that will be/has been used to create web (HTTPS, once you've updated) requests. But it's doing it in a non-async method. This isn't really an issue, but aiohttp thinks it is, so it spews out a bunch of warnings.

I'm glad the other part was able to help. You should be fine with the updated code (HTTP->HTTPS).
